# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bulat.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x62ulat.proto\x12\x0btransaction\"I\n\x10SumAmountRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\x12\x12\n\nstart_time\x18\x02 \x01(\x03\x12\x10\n\x08\x65nd_time\x18\x03 \x01(\x03\")\n\x11SumAmountResponse\x12\x14\n\x0ctotal_amount\x18\x01 \x01(\x01\x32\x62\n\x11TransactionServer\x12M\n\nsum_amount\x12\x1d.transaction.SumAmountRequest\x1a\x1e.transaction.SumAmountResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bulat_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SUMAMOUNTREQUEST']._serialized_start=28
  _globals['_SUMAMOUNTREQUEST']._serialized_end=101
  _globals['_SUMAMOUNTRESPONSE']._serialized_start=103
  _globals['_SUMAMOUNTRESPONSE']._serialized_end=144
  _globals['_TRANSACTIONSERVER']._serialized_start=146
  _globals['_TRANSACTIONSERVER']._serialized_end=244
# @@protoc_insertion_point(module_scope)
